### ISSUE TITLE
Fatal error when upgrading from 1.07 to 1.08

### ISSUE THREAD

**Issue by jacmaes** [SkyLundy/Fluency#5] opened 2024-04-23 18:36 UTC
I'm on PW 3.0.236. Here's the error:

Fatal Error: Uncaught TypeError: Fluency\DataTransferObjects\FluencyEngineSelectData::fromArray(): Argument #1 ($data) must be of type array, null given, called in site/modules/Fluency/app/DataTransferObjects/FluencyDTO.php on line 58 and defined in site/modules/Fluency/app/DataTransferObjects/FluencyEngineSelectData.php:34

**Comment by jacmaes** [comment] 2024-04-29 16:15
Exact same error on another server.

**Comment by SkyLundy** [comment] 2024-04-29 17:19
I see this. It's caused by the revamp of how the translation engine data is stored when changing from serialization to JSON in the most recent version to address [this issue](https://processwire.com/talk/topic/24567-fluency-the-complete-translation-enhancement-suite-for-processwire/?do=findComment&comment=239102).

I'm going to work on pushing a fix to solve the upgrade issue, in the meantime if you uninstall then reinstall the module it should get you back on your feet.

**Comment by SkyLundy** [comment] 2024-04-29 19:53
@jacmaes I've pushed an update to development, I've tested as much as I can on my end using the same version you mentioned. If you can give that a shot and tell me if it fixed it, I'd appreciate the help!

[https://github.com/SkyLundy/Fluency/tree/development](https://github.com/SkyLundy/Fluency/tree/development)

**Comment by jacmaes** [comment] 2024-05-15 09:43
Sorry for the delay. Yep, the dev version seems to be working just fine. Thanks!

**Comment by SkyLundy** [comment] 2024-05-28 17:02
This will be merged into the next release. Thanks for reporting!

**Comment by jacmaes** [comment] 2024-06-18 15:03
Reopening this issue because it seemed to work fine, but when saving a page with the latest dev version:

Arrgh… Fatal Error: Uncaught TypeError: Fluency\DataTransferObjects\FluencyEngineSelectData::fromArray(): Argument #1 ($data) must be of type array, null given, called in site/modules/Fluency/app/DataTransferObjects/FluencyDTO.php on line 58 and defined in site/modules/Fluency/app/DataTransferObjects/FluencyEngineSelectData.php:34

**Comment by SkyLundy** [comment] 2024-06-18 16:30
@jacmaes

- Is this during a module upgrade or on a fresh module reinstall?
- How many languages do you have configured?
- Do you have a translation engine selected?
- Did you reconfigure and re-save the module config?

**Comment by SkyLundy** [comment] 2024-06-18 16:53
@jacmaes Just to confirm- you were able to get it working by downloading the dev branch?

I haven't pushed the upgrade yet, the fix for this issue is a version bump to 1.0.9. Haven't had the chance but will work on it.

**Comment by jacmaes** [comment] 2024-06-18 16:58
It looks like it works mostly with the dev branch: I've worked on the site for half an hour, saved a few pages multiple times without errors. But then I suddenly received a PW notification by email at the end of my session (after the 30 mins) with: 

Oops… Fatal Error: Uncaught TypeError: Fluency\DataTransferObjects\FluencyEngineSelectData::fromArray(): Argument #1 ($data) must be of type array, null given, called in site/modules/Fluency/app/DataTransferObjects/FluencyDTO.php on line 58 and defined in site/modules/Fluency/app/DataTransferObjects/FluencyEngineSelectData.php:34

But in the admin, no error.

**Comment by SkyLundy** [comment] 2024-06-18 17:04
> First, I upgraded the module via the PW admin without thinking when I noticed that an update (to 1.08) was available. That immediately caused the fatal error mentioned in the beginning of this thread. So I downloaded the latest dev version and replaced it manually. So I had to reconfigure and resave the module config.

I think the error email you received was from the error you experienced when upgrading. If you haven't experienced any issues after manually upgrading from the development branch and haven't received any more email then the issue was resolved.

I think that the delay of 30 minutes between the error and your email was just a side effect of how long it took the email to get sent, how long it took to get processed, and then how long it took to get delivered to your inbox.

**Comment by jacmaes** [comment] 2024-06-18 17:08
You're probably right. The thing is, when I first experienced issues by upgrading via the PW admin, I received a series of error emails immediately, like 8 in a row. The sudden 30-minute delay seems strange, but entirely possible. Let's assume it's fixed on the dev branch. I don't work regularly on that particular site, but I'll let you know if not.

**Comment by SkyLundy** [comment] 2024-06-18 17:13
I do agree that it's odd, but that's the only explanation I can think of. Since it's a fatal error you would have seen that issue again when translating after upgrading the module.

I'm pushing 1.0.9 shortly which will solve all upgrade issues going forward. Appreciate the help troubleshooting and testing. I'll close this issue as resolved after the new release.

**Comment by SkyLundy** [comment] 2024-06-18 17:38
Closing with [1.0.9 release](https://github.com/SkyLundy/Fluency/releases/tag/v1.0.9) and update in modules directory for upgrading in ProcessWire installations

**Closed by SkyLundy** 2024-06-18 17:38 UTC
Labels: bug, bug verified, verify fix
